mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/24.

Use a `Map` for `tlVersionIntroduced`

---

settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

Fixes #47. They were next to each other in sbt-spiewak, and I must have forgot them :)

Add missing settings

---

.github/workflows/ci.yml
sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala

Fixes #49. I made the mistake when removing the old workaround in #45, by removing actual useful non-workaround stuff. My bad.

Fix publish step

---

versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/51. Mostly reshuffling existing code, and added some comments.

Fix tag-based versioning

---

.github/workflows/ci.yml
README.md
kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala
sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala

I'm almost definitely being anal about this, but maybe one day somewhere it will save someone's bacon.

Namespace the release commands

---

build.sbt

We are self-hosting, so we can use our own features :)

Cleanup our build

---

mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala

Set tlVersionIntroduced default at build-level

---

.github/workflows/ci.yml
ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala

Small wins inspired from https://github.com/typelevel/sbt-typelevel/issues/93.

Check headers/fmt, mima, docs on primary Java only

---

project/build.properties

(cherry picked from commit 919e40054accde4823ba42c0307b20c01264be04)
Closes https://github.com/typelevel/sbt-typelevel/pull/129.

Update sbt to 1.6.2

---

docs/faq.md

This one is _actually_ a FAQ. Definitely looking for feedback, since explaining this requires covering early semantic versioning and various notions of compatibility.
@tpolecat if you have a chance, I would especially appreciate your thoughts since we discussed this topic previously. Thanks :)

Add FAQ about base version

---

README.md
docs/index.md

sbt-typelevel has its own channel now :')

Add discord links

---

.github/workflows/ci.yml
ci-signing/src/main/scala/org/typelevel/sbt/TypelevelCiSigningPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/147.
```
-i, --ignore-garbage  when decoding, ignore non-alphabet characters
```

Ignore garbage when decoding PGP secret

---

sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala

Reverts typelevel/sbt-typelevel#150. Closes https://github.com/typelevel/sbt-typelevel/issues/152.

Revert "Use unique names for publish resolvers"

---

github-actions/src/main/scala/org/typelevel/sbt/gha/GitHubActionsPlugin.scala
kernel/src/main/scala/org/typelevel/sbt/kernel/GitHelper.scala
versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala

Some optimizations to silence the $IDE linter mostly.

Micro-optimizations of using collections

---

README.md
docs/index.md

I hope this makes it clearer what this plugin does.

Revamp README, intro

---

docs/index.md

Add info blurb about sbt-typelevel vs sbt-typelevel-ci-release

---

docs/faq.md

Add mdoc --watch suggestion in another terminal

---

mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala

Fixes a regression introduced in https://github.com/typelevel/sbt-typelevel/pull/176 where `tlVersionIntroduced` was no longer respected on the project-level (it was only using `ThisBuild`-level setting).

Respect project-level `tlVersionIntroduced`

---

.github/workflows/ci.yml
github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala

https://github.com/actions/checkout/releases/tag/v3.0.0

Update to actions/checkout@v3

---

README.md
build.sbt
docs/customization.md
docs/directory.conf
docs/faq.md
docs/index.md
docs/site.md
site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/186.
As usual, there is much room for improvement, but this is a small step forward.

Add page for sbt-typelevel-site plugin

---

site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala

Add `index.html` to API url

---

sonatype/src/main/scala/org/typelevel/sbt/TypelevelUnidocPlugin.scala

Fool me once, shame on you, fool me twice, shame on me.
Fixes https://github.com/typelevel/sbt-typelevel/issues/214.

Forward doc task to unidoc task

---

settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

This is a breaking change for 0.5.

Set default `tlJdkRelease := Some(8)`

---

docs/index.md
docs/site.md

And make the example project a bit more fun 🍯

Demonstrate how to add unidoc project filter in docs

---

settings/build.sbt
settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

Closes:
- https://github.com/typelevel/sbt-typelevel/issues/239
- https://github.com/typelevel/sbt-typelevel/issues/248

Useful source-related settings

---

versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala

Philosophically, if there are uncommitted changes then arguably any tags on the HEAD commit are no longer relevant and should not be used for versioning. (If you made a new commit with the current changes, then they definitely wouldn't be.)
Practically, if your HEAD commit is tagged 0.3.0 and you bump your base version to 0.4 _without_ committing, then attempting to load sbt-typelevel will error with:
```
[error] Your current version 0.3.0 cannot be less than tlBaseVersion 0.4
```
This error is a fail-safe to prevent publishing of an 0.3.0 when the base version is 0.4, since that would be bad. But if your git tree is dirty, then your version will not be v0.3.0 anyway, so this error is pointlessly confusing and annoying.
So, if the git tree is dirty, ignore the tags for the purposes of …

Don't use tags for versioning if git tree is dirty

---

site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala

A more sensible fix for https://github.com/typelevel/sbt-typelevel/issues/276.
Instead of relying on dates, all we need to do is look at the current version and use that to determine which tags are in fact previous releases.
For a concrete situation where this is relevant: in http4s, e.g. the series/0.23 branch also contains the v1.0.0-M23 tag, because until 0.23 was branched off it was the 1.0.0 dev branch. This confused the current algorithm, which was selecting v1.0.0-M23 as the latest version. However, the build knows that its current version is 0.23.x via the `version` setting, so it can use that to "re-calibrate" and discard those milestone tags.

Determine previous releases in site plugin by current version

---

.github/workflows/ci.yml
build.sbt
sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
sonatype/src/main/scala/org/typelevel/sbt/TypelevelUnidocPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/226. Closes https://github.com/typelevel/sbt-typelevel/pull/265.

Use sonatype as fallback for API URL

---

versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/261.

Tagged version is greatest-valued tag

---

scalafix/src/main/scala/org/typelevel/sbt/TypelevelScalafixPlugin.scala

Add typelevel-scalafix to the sbt-typelevel-scalafix dependencies

---

docs/faq.md

Adds a FAQ about the ScalaJS version management
See https://github.com/typelevel/otel4s/pull/18

Add FAQ about ScalaJS version

---

core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyAction.scala
mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyCondition.scala
settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

Re-enable unused warnings for scala 2.12

---

core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala

Also use `session clear` instead of `reload` at the end.

Add `doc` to `prePR` command alias

---

kernel/src/main/scala/org/typelevel/sbt/kernel/V.scala
kernel/src/test/scala/org/typelevel/sbt/kernel/VSuite.scala

Resolves https://github.com/typelevel/sbt-typelevel/issues/260

Do not require binary compat on 0.0.z versions

---

core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/345.
Note that this PR will be negated in 0.5.x if we go through with https://github.com/typelevel/sbt-typelevel/pull/243.

Set CI JDK via `tlJdkRelease` setting

---

project/build.properties

Reverts typelevel/sbt-typelevel#383

Revert "Update sbt to 1.7.2"

---

site/build.sbt

Reverts typelevel/sbt-typelevel#384

Revert "Update mdoc, sbt-mdoc to 2.3.6"

---

.github/workflows/ci.yml
.mergify.yml
build.sbt
github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/301.
https://github.com/marketplace/actions/github-action-for-graalvm

Use new setup-graalvm action

---

ci-release/src/main/scala/org/typelevel/sbt/TypelevelCiReleasePlugin.scala
ci/build.sbt
ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
project/ci.sbt

Closes https://github.com/typelevel/sbt-typelevel/issues/311.

Disable publishing-related steps in CI plugin

---

github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala
settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/336.

Move GitHub-related settings to GitHub plugin

---

.github/workflows/ci.yml
github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/421.

Run `sbt update` on cache miss

---

settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

For scala version 3.2.1+.
I have very little knowledge of sbt, so open to any critique!

Add Inkuire for scaladoc

---

site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
site/src/main/scala/org/typelevel/sbt/site/TypelevelHeliumIcon.scala

- https://github.com/typelevel/governance/pull/97

Replace Twitter icon with Mastodon icon

---

.github/workflows/ci.yml
.mergify.yml
ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala

Saves a setup step and will work perfectly fine.

Steward config validation job can use default Java

---

.scala-steward.conf

Some follow-up to https://github.com/typelevel/sbt-typelevel/pull/510 😞

Pin Laika updates

---

core/build.sbt

Most Typelevel projects are using this now.

Add `sbt-scala-native-crossproject` to core

---

.github/workflows/ci.yml
ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
no-publish/src/main/scala/org/typelevel/sbt/NoPublishPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/442.

Make dependency submission ignore non-compile scopes and no-publish projects

---

github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/447.

Populate `releaseNotesURL` setting

---

.github/workflows/ci.yml
.mergify.yml
build.sbt
github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/509.

Fix indentation

---

.github/workflows/ci.yml
github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/308.

Don't upload artifacts for no-publish projects

---

ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/426.
The CI matrix is often used to run tests on different OSes, Javas, browsers, etc. These all share the same sources so there is no need to re-check scalafmt, scalafix, mima, scaladocs, etc. This updates the condition used to filter these steps to also consider additional axes in the matrix besides java and os.

Run ci check steps only for primary value of axes

---

.github/workflows/ci.yml
ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala

scalafix is basically like an enhanced compile. besides the test step may need linking (slow) and actually running the tests. I think it makes sense to run scalafix first.

Run scalafix before test

---

.github/workflows/ci.yml
.mergify.yml
build.sbt
site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala

We use macOS and Windows in Cats Effect CI, so we should test build plugin support for that.

Add macos and windows to ci

---

ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
docs/customization.md
docs/site.md
settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

* resolve merge conflict
* fix outdated links
* update plugins with their settings, tasks and commands

update plugin doc

---

settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

Added the wiki syntax flag for non-pure Scala 3 projects, since scaladoc2 uses the wiki syntax with no markdown support. Pure Scala 3 builds may just use markdown support as intended.

Scaladoc3 Wiki Syntax Flag

---

mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala

skip mima task, if no artifacts should be published

---

settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

Fixes https://github.com/typelevel/sbt-typelevel/issues/577.

Also add `scalac-compat` to `Test` scope

---

.github/workflows/ci.yml
no-publish/src/main/scala/org/typelevel/sbt/NoPublishPlugin.scala

Hopefully this is the last one! h/t Marco for this fix 🙏

Fix rendering of `modules-ignore`

---

.github/workflows/ci.yml
.mergify.yml
ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala

This causes an issue in GHE runners that may not use the default java version of 11.

Revert #508

---

.github/workflows/ci.yml
github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala

https://github.com/actions/checkout/releases/tag/v4.0.0

Update to checkout v4

---

site/build.sbt

Reverts typelevel/sbt-typelevel#635

Revert "Update laika-sbt to 0.19.4"

---

build.sbt
scalafix/src/main/scala/org/typelevel/sbt/ScalafixProject.scala
scalafix/src/main/scala/org/typelevel/sbt/ScalafixProjectMacros.scala
scalafix/src/main/scala/org/typelevel/sbt/TypelevelScalafixPlugin.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/304.

Upstream `ScalafixProject`

---

core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala

Since scalafix rewrites source code, the formatting might need some fixing afterwards.

Run scalafix before scalafmt in `prePR`

---

settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala

See https://github.com/scala/scala3/pull/20199

Use stable option for kind-projector in 3.5+

---

core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala

Closes https://github.com/typelevel/sbt-typelevel/issues/735. Alternative to https://github.com/typelevel/sbt-typelevel/pull/738.

Disable CI snapshots if publishing to Central host

---

.github/workflows/ci.yml
github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala

https://github.com/sbt/setup-sbt

use `sbt/setup-sbt` to install sbt on all platforms

---

.github/workflows/ci.yml
.mergify.yml
build.sbt

graalvm@17 is no longer available (see failing CI on #762, caused by the licensing changes called out in [this comment](https://github.com/actions/setup-java/pull/501#discussion_r1789114879))
so bumping us up to graalvm@21

bump to graalvm@21
