- .scala-steward.conf
I think this should prevent PRs like https://github.com/typelevel/sbt-typelevel/pull/27.
> Pin to Scala 2.12.x

- .scala-steward.conf
Currently http4s-dom and outwatch are stuck on SJS 1.7 due to problems in https://github.com/scalameta/mdoc/pull/597.
> Pin Scala.js to 1.7.x

- build.sbt
- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
- sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala
Two changes here:
1. Add a `tlCiReleaseTags` option, default `true`. This is so you can disable releasing tags from CI, good for projects like CE that may want CI snapshots but not CI tags.
2. Merge the `tlCiReleaseSnapshots` and `tlCiReleaseBranches` into a single setting `tlCiReleaseSnapshotBranches`, where you directly specify the branches you want snapshots from. Default is empty, which causes no snapshots to be released.
> Improve CI release config

- .github/workflows/ci.yml
- build.sbt
- ci/build.sbt
- ci/src/main/scala/org/typelevel/sbt/CrossRootProject.scala
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- core/build.sbt
- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/34.
This introduces a `tlCrossRootProject` helper for creating the "root" aggregate project. It:
1. Generates `root`, `rootJVM`, `rootJS`, and `rootNative` projects (all set to no-publish)
2. Automatically sorts any aggregated projects and cross-projects into their appropriate roots (`root` itself collects everything)
3. Adds an axis to the CI matrix for platform, but only adds jobs for platforms which are represented in the build
I've demonstrated/tested `tlCrossRootProject` on this build, where it adds a single `ciJVM` job to the matrix since there are no JS or native project in this build. (Note that we now also have a `rootJS` and `rootNative` project that are empty, just a small nuisance I hope.)
> Introduce `tlCrossRootProject`

- .github/workflows/ci.yml
- sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala
- versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/42.
For context, this is the "race condition" where if a commit is pushed to GH with a tag and CI release is enabled for both tags and snapshots, two publish jobs will start simultaneously and both will have the identical (tagged) version. The workaround is to first push the commit and wait for its (snapshot) publish job to complete, then push the tag separately to trigger the second publish job.
Fixing this problem is also important for projects that may want CI release for snapshots but don't want CI release for tags, such as CE—there needs to be a way for the snapshot publish job to ignore the tags.
The solution here definitely makes me feel a bit queasy: it changes our versioning algorithm depending on the presence/value of an …
> Take 2: fix CI release/snapshot race condition

- versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala
A followup to #52 that fixes the logic used to set `isSnapshot`.
> Fix snapshot derivation logic

- README.md
- build.sbt
- ci-release/src/main/scala/org/typelevel/sbt/TypelevelCiReleasePlugin.scala
- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
- sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala
Manual triggering was a pattern I copied from sbt-spiewak which doesn't make sense here.
> Automatically trigger ci-release plugins

- .scalafmt.conf
Keep getting a warning about this. I assume it's because of our scalac flags.
Edit: this probably https://scalameta.org/scalafmt/docs/configuration.html#scala-2-with--xsource3
> Set scalafmt dialect to `scala212source3`

- kernel/src/main/scala/org/typelevel/sbt/kernel/GitHelper.scala
Fixes #75 and fixes #76. A simple change to make the `previousReleases` strict, so it doesn't include any tags on the current commit as a previous release.
> Make `previousReleases` strictly previous

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
Currently headers are automatically generated on compile. This is a bad default and leads to mishaps in CI like https://github.com/http4s/http4s/issues/5917.
Headers must now be manually generated with `headerCreateAll`. This is consistent with formatting, which is also invoked manually. All of this is covered in the existing `prePR` command, although perhaps we need a "lighter" alias that just does headers+formatting without clean-compiling like `prePR` does.
> Don't generate headers automatically on compile

- docs/index.md
> Add docs on how to cut a release

- .github/workflows/ci.yml
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/89. Helps to mitigate https://github.com/typelevel/sbt-typelevel/issues/81.
Since the artifacts are only downloaded if the publish job runs, it makes sense that artifact upload should use the same condition.
> Only upload artifacts if publishing

- build.sbt
The changes in https://github.com/typelevel/sbt-typelevel/pull/92 are good, but a little too breaking. For example the following `build.sbt` would stop working since the sonatype credentials are now expected to be provided on the step itself.
```scala
ThisBuild / githubWorkflowPublish := Seq(WorkflowStep.Sbt(List("tlRelease")))
```
There's no real urgency for this feature, so we can keep it on ice until v0.5.0 when the other breaking change will be making s01 the default host.
> Bump base version to 0.5

- .github/workflows/ci.yml
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/95.
It no longer assumes that the project id is `docs`. The input directory still defaults to `docs/`, but this is inherited from mdoc itself and thus can be changed in whatever the usual manner is.
> Make site plugin more robust

- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
Ack, I bungled this release. My changes in https://github.com/typelevel/sbt-typelevel/pull/98 work perfectly for the crossed case but accidentally appended a trailing `-` to artifact ids for vanilla, non-crossed projects.
E.g. see https://github.com/typelevel/mouse/runs/4950242981?check_suite_focus=true
Time to get serious about adding regression tests 😞
> Fix trailing dash in upload artifact ids

- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
Only if there's not already something set.
> Automatically populate `apiURL` with javadoc.io

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
@danicheg reminded me in https://github.com/typelevel/mouse/pull/305 how confusing it is to use the last Scala as the default. Turns out that `ThisBuild / scalaVersion` is fine, I thought it would generate different workflows depending on `++` but it seems not.
> Read default scala version from `ThisBuild`

- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
- mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala
A (better) alternative to https://github.com/typelevel/sbt-typelevel/pull/101. This was a good lead.
1. Automatically sets `skip := true` if `crossScalaVersions` for a project does not contain the current `scalaVersion`.
2. Makes `mimaReportBinaryIssues` skip-aware.
I'm going to a snapshot this branch to test it out in frameless. Update: seems to work.
> Integrate with `skip`

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
Another prePR-style alias, but this one skips the clean compile and is intended only for bots. Since sbt-typelevel absorbs so many plugins (sbt-gh-actions, sbt-scalafmt, etc.) this command will provide a unified way for scala-steward to run all the necessary post-upgrade steps. Will also be useful for https://github.com/typelevel/sbt-typelevel/issues/69 and any other ideas we come up with that require sbt-typelevel-managed files.
> Add `tlPrePrBotHook`

- ci/src/main/scala/org/typelevel/sbt/CrossRootProject.scala
I've always thought these are aliases so not gonna lie, I chose the one that sounded cooler 🤦 
FTR `fastOptJS` is legacy and doesn't support some of the newer features that `fastLinkJS` does.
> `fastOptJS` -> `fastLinkJS`

- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
This is the same condition used to determine whether to generate the publish job at all.
> Don't generate artifact upload steps if not publishing

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
This is scope creep: the settings plugin is focused on scalac and javac flags and should be usable in non-libraries.
The version scheme is already set in the versioning plugin anyway, where it makes sense.
Breaking enough that it goes into 0.5.
> Don't set version scheme in settings plugin

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
A shortcut `License.Apache2` was added in https://github.com/sbt/librarymanagement/pull/395 but I'm hesitant to unnecessarily rely on new sbt features for builds stuck on old versions for whatever reason.
> Fix Apache 2.0 license url

- ci/src/main/scala/org/typelevel/sbt/CrossRootProject.scala
This one respects the `scalaJSStage` setting and delegates to `fastLinkJS` or `fullLinkJS` as appropriate.
> Use `scalaJSLinkerResult` for linking step

- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
Temporarily inlines the fix from https://github.com/xerial/sbt-sonatype/pull/279 with an unfortunate amount of duplication.
> Use unique names for publish resolvers

- versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala
The base version concept can be confusing. Hopefully this will help people set it correctly.
> Error (helpfully) if base version is not `x.y`

- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
Cherry-picks a fix out of https://github.com/typelevel/sbt-typelevel/pull/119.
> Set javadoc.io url only when appropriate

- .github/workflows/ci.yml
- build.sbt
- github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
Cherry-picks various improvements for the site plugin out of https://github.com/typelevel/sbt-typelevel/pull/116.
> site plugin improvements

- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
Followup to https://github.com/typelevel/sbt-typelevel/pull/117. Closes https://github.com/typelevel/sbt-typelevel/issues/140.
https://github.com/typelevel/sbt-typelevel/issues/140 was initially concerning but it turned out the project where I saw that was misconfigured actually.
After experimenting with the snapshot I'm reasonably confident that for most projects this `skip` thing works very nicely.
There are certain situations where it may prove to be problematic, such as backpublishing tags for kind-projector or maybe in the community build which is specifically trying to build projects on a scala version not configured in the project build.
In any case, it would be foolish not to provide an escape-hatch.
~~This should be the last fix going into 0.4.4.~~ I lied. I want to get some of …
> Add `tlSkipIrrelevantScalas` setting

- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
- mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala
Fixes #140, this time for real.
Two changes:
1. Don't set `skip := true` for a whole project. Instead set it task-by-task, for tasks where skipping is known to be "safe".
2. Make this feature opt-in. More builds broke than builds that actually need this. It's a good default in theory, but in practice there are too many complex interactions that makes stuff break in confusing ways.
> More responsible skipping

- kernel/src/main/scala/org/typelevel/sbt/kernel/GitHelper.scala
Let's save a few nanoseconds on the loading of the project. Though it's only the hypothesis that sorting using git is faster. But I can bet it's so.
> Optimize sorting in the `GitHelper.previousReleases`

- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/161.
When I wrote that issue I also mentioned using `WorkflowStep` helpers (I had in mind the ones for checking out the repo and setting up Javas) but on second look I think `githubWorkflowJobSetup` is the right thing to use. 👍
> Use `laikaSite / target` to get site directory

- docs/index.md
The example in the quickstart was just a little sparse. This fleshes it out with a more complete example build. IMHO it's still super simple considering all that it does 😁
> Demonstrate a "minimum viable project" in the quick start

- mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala
We previously debated its usefulness in https://github.com/typelevel/sbt-typelevel/pull/46, but now I'm convinced.
1. `mimaPreviousArtifacts` is at the project level, but often you want to filter botched releases at the build-level. `tlMimaPreviousVersions` is build-level.
2. Some projects add extra versions, like cats includes the 1.x series for some modules.
3. Some projects are just weird, like scalacheck has this pvp version thing going on.
So yeah, I'm convinced :)
> Add `tlMimaPreviousVersions` setting

- .github/workflows/ci.yml
- github-actions/src/main/scala/org/typelevel/sbt/gha/JavaSpec.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/107. Integrates sbt-typelevel with [typelevel/jdk-index](https://github.com/typelevel/jdk-index) and [typelevel/download-java](https://github.com/typelevel/download-java).
Not all the distributions currently made available in the plugin are included in the typelevel/jdk-index, so these fallback to the old workflow steps. And similar for specific versions of GraalVM, since the index always points to the latest.
There will be minor breakage if someone was specifying a _full_ Java version (`"17"` vs `"17.0.2"`) but that's probably pretty unusual and not a good idea in general. We may want to consider requiring an `Int` here in the future instead of a `String`.
cc @vasilmkd
> Use typelevel jdk index for managing Java

- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
This PR adds a single command `tlSitePreview` which runs both `mdoc --watch` and `laikaPreview` simultaneously, for a cohesive live-reload editing experience. Thanks to @Quafadas for reminding me about this in https://github.com/typelevel/sbt-typelevel/issues/186#issuecomment-1050321968.
cc @jenshalm (sorry for all the noise this week!): I thought you may be interested what this looks like, since you also mentioned this problem while working on the http4s site.
Unfortunately I had to copy the implementation of `laikaPreview` here. But, I wonder if the next version of Laika can define a `Task[() => ()]` `laikaStartPreview` that starts the server and returns the shutdown hook. `laikaPreview` can then be implemented using that, but it also makes it easier to integrate with other tooling like …
> Add `tlSitePreview`

- docs/customization.md
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
Fixes #137. Implemented the way as @armanbilge suggested.
> Add the `tlSitePublishTags` setting

- kernel/src/main/scala/org/typelevel/sbt/kernel/GitHelper.scala
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
1. Add a `PRERELEASE_VERSION` mdoc variable, which is guaranteed to be the latest released version _including pre-releases_ (Ms, RCs, etc.). This is in addition to existing `VERSION` (the latest stable release) and `SNAPSHOT_VERSION` (the current version in the build).
2. If there are no stable releases in the current _binary series_, let the `VERSION` variable adopt the latest pre-release version instead.
3. When looking for the latest `VERSION`, consider both current _and_ previous tags (i.e., not _strictly_ previous).
> Better versioning in site plugin

- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
- site/src/main/scala/org/typelevel/sbt/site/TypelevelHeliumExtensions.scala
Laika defaults to Scala 2 highlighting for `scala` sources, see:
- https://github.com/planet42/Laika/discussions/268
> Enable syntax highlighting for Scala 3 automatically

- site/build.sbt
Reverts typelevel/sbt-typelevel#112
Mdoc 2.3.x is currently plagued by:
- https://github.com/scalameta/mdoc/issues/615
> Revert "Update mdoc, sbt-mdoc to 2.3.0"

- docs/site.md
Using `unidoc` as the project name conflicts with Unidoc's scope.
> Use `unidocs` as project name in `unidoc` example

- site/build.sbt
This PR updates us to sbt-mdoc 2.3.2 which includes the Polytype fix for PPrint thus resolving the issue motivating https://github.com/typelevel/sbt-typelevel/pull/224
https://github.com/com-lihaoyi/PPrint/pull/79
https://github.com/scalameta/mdoc/pull/636
> Update sbt-mdoc to 2.3.2

- github/src/main/scala/org/typelevel/sbt/TypelevelScalaJSGitHubPlugin.scala
According to scaladoc:
> In batch mode, the linker can throw away intermediate state that is otherwise maintained for incremental runs.
No idea if it will make a meaningful difference, but we definitely don't need incremental state in CI.
> Use SJS linker batch mode in CI

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/201.
TIL `inConfig`. This change should make it possible to set different values for these settings in the `Compile` and `Test` scopes. Examples:
- fatal warnings in compile, disabled in test
- JDK 8 in compile, JDK 11 in test
> Move `tlFatalWarnings` and `tlJdkRelease` into per-config scope

- github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/249. Two changes:
1. First check for an `upstream` remote, then fallback to `origin`. This way forks do the right thing.
2. Log the detected SCM info in the console, to avoid future oopsies.
> Smarter SCM info detection

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/253 by effectively reverting https://github.com/typelevel/sbt-typelevel/pull/250.
I though I was very clever in https://github.com/typelevel/sbt-typelevel/pull/250 but I neglected to realize that the `Test` config inherits from the `Compile` config. So, if you setting scalac and javac options additively, then the settings in the `Test` scope are not independent of those in `Compile`.
sbt-tpolecat recently navigated this in https://github.com/DavidGregory084/sbt-tpolecat/pull/58, and AFAICT was able to do so because its sets scalac options all at once e.g. `:=` instead of `++=`. But that's too big a change for now.
> Revert #250 which moved scalac/javac options to scope-specific settings

- README.md
- build.sbt
- docs/index.md
This PR adds a typelevel.g8 section to the index as part of the Quick Start section.
Additionally, it adds a link to the README.
> Add typelevel.g8 section to docs

- docs/index.md
1. Mention the sbt-typelevel-site plugin, since it's part of the g8.
2. Make the GitHub Actions setup a separate section.
> Tweak quickstart to better reflect sub-sections

- docs/index.md
The linked list is not _exactly_ a list of sbt-typelevel adopters, but it's a very good proxy unless the typelevel/download-java action takes off of its own accord.
https://github.com/typelevel/download-java/network/dependents
> Link to list of adopters

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
- site/src/main/scala/org/typelevel/sbt/site/TypelevelHeliumExtensions.scala
scaladoc before 2.13 doesn't resolve links into the Java SE javadocs.  This adds fallback apiMappings for various JVMs so `doc` tasks don't crash.
> Add API mappings for Java

- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/247.
This PR adds settings to the `TypelevelCiPlugin` to toggle various steps in the generated CI workflow.
This makes it easy for individual builds/projects to turn these steps on/off, so that a project can still get scalafmt checks for example even if they don't want header checks or scalac settings.
In sbt-typelevel v0.5.0 I will make all these false by default in the `TypelevelCiPlugin`, and enable them as appropriate in the `TypelevelCiReleasePlugin` and `TypelevelPlugin`. This will make it easier to use the `TypelevelCiPlugin` for non-publishing applications developed on GitHub.
> Make default CI steps togglable

- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
Really hate how brittle this workaround is.
I wonder if a better strategy is to never have a "hole" in the matrix that requires tasks to be skipped. A project can always "compile" for Scala 3 with empty sources and no dependencies, you just don't want to _publish_ it maybe. So there needs to be a way to enable the `NoPublishPlugin` per scala version. Something to think about for 0.5.0.
> Skip doc task if irrelevant

- build.sbt
- github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala
So turns out I have opinions about this :) closes https://github.com/typelevel/sbt-typelevel/issues/277.
It creates an entry like this:
```xml
<developer>
<id>typelevel</id>
<name>sbt-typelevel contributors</name>
<url>https://github.com/typelevel/sbt-typelevel/contributors</url>
<email>@typelevel</email>
</developer>
```
This is breaking for anyone setting developers in their build like `++=`, so it goes to 0.5.
> Auto-populate developers w/ GH info

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
See https://github.com/typelevel/sbt-typelevel/issues/177#issuecomment-1146580184 for context.
Strategically named this branch `update/ignore-me` to see if it works right.
> Don't run CI on `update/*` branches

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/177.
Same ideas as https://github.com/typelevel/sbt-typelevel/pull/291. If you don't want CI on a branch (most likely because it is going to become a PR) simply prefix it with `pr/`. Easy.
> Don't run ci on `pr/**` branches

- docs/index.md
Following https://github.com/typelevel/typelevel.g8/pull/28
> Add startYear to example build

- build.sbt
- docs/faq.md
- docs/index.md
- project/build.sbt
H/t @valencik for the idea and snipe. For the record it absolutely wasn't worth it 😂
> Auto-populate startYear and SJS version in docs

- docs/site.md
Sharing the learnings from https://github.com/typelevel/otel4s/issues/28.
> Detailed instructions to configure repo settings for site publishing

- .mergify.yml
- build.sbt
- mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyAction.scala
Most of our OSS projects use the `request_reviews` and `update` Mergify actions, which aren't supported yet. e.g. https://github.com/Dwolla/fs2-pgp/blob/main/.mergify.yml
We have also typically used merge queues instead of merging directly, but I'm not sure how important that is. I remember we switched from "strict" merges when [Mergify deprecated them](https://blog.mergify.com/strict-mode-deprecation/), but maybe that was overkill for our needs. I'll play with it and see; we can always add that in a future PR.
> Add request_reviews and update Mergify actions

- .github/workflows/ci.yml
- .mergify.yml
- build.sbt
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/327.
This also adds a JDK 17 job to CI as part of the replication. I think this is a good addition anyway.
> Only download artifacts for primary OS/JDK

- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
- site/src/main/scala/org/typelevel/sbt/site/TypelevelHeliumExtensions.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/319.
> Add `/api` path to site that forwards to API url

- github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala
- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/323.
> Configure scaladoc3 `-source-links` and friends

- build.sbt
- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
- versioning/src/main/scala/org/typelevel/sbt/TypelevelVersioningPlugin.scala
> Expose versioning info in version plugin

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/326.
This adds a job that submits the projects dependencies to GitHub via
https://github.com/scalacenter/sbt-dependency-submission
Results should go here:
https://github.com/typelevel/sbt-typelevel/network/dependencies
Annoyingly I don't think we'll be able to see any results yet. I've targeted this at the `main` branch since I'm not sure yet how stable the action is, but GitHub only cares about the default branch which is `series/0.4`.
> Add dependency submission job to CI

- kernel/src/main/scala/org/typelevel/sbt/kernel/V.scala
- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
The intent is to keep as many warnings as possible by still preserving backward compatibility between Scala 2.12 and 2.13 series (which is not always possible though).
For more details see a discussion in typelevel/cats-effect#3104.
> Tune Scala compiler warnings

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
The `scalacOptions` for `console`/`consoleQuick` commands were broken in #312 and #344
This PR should fix that.
> Fix console/scalacOptions

- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
Of note, this will yield a URL that does not exist when:
- You run this on a dirty git workspace and thus have a timestamp as part of your snapshot
- You run this on a commit that has not had a snapshot published
> Fallback to apiURL if javadocioUrl does not exist

- build.sbt
- kernel/src/test/scala/org/typelevel/sbt/kernel/VSuite.scala
This PR:
- adds an `munit` test suite to the kernel module
- adds basic tests for version handling and bincompat
> Adding tests around version handling

- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
This came up in https://github.com/http4s/http4s-curl/pull/8 where I used explicitly named ubuntu versions instead of the usual `ubuntu-latest`. Then the publish job was no longer matching.
> Use workflow OSes for publish job

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/issues/352
> Use `tlJdkRelease` for JDK api mappings

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Fixes this error, seen in builds using the `tlJdkRelease` option with Scala 2.13.9.
```
[error] -target is deprecated: Use -release instead to compile against the correct platform API.
```
Relevant PR:
- https://github.com/scala/scala/pull/9982
> Do not use deprecated `-target` option on 2.13.9+

- .github/workflows/ci.yml
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativeKeys.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowJob.scala
Using `sbt '++2.13' test` works, but `sbt '++3' test` does not. However, both `sbt '++ 2.13' test` and `sbt '++ 3' test` work, and the space is included in the [sbt documentation](https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Switching+Scala+version).
> add a space to the Scala version selector command

- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
> introduce `CompileTime` custom configuration

- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
I think I forgot to update this in https://github.com/typelevel/sbt-typelevel/pull/284.
> Use `hostedApiUrl` as fallback for `apiURL`

- .github/workflows/ci.yml
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
I try to avoid major bumps of dependencies in minor versions, but 0.4 will eventually cease to function without this.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Bump actions to Node 16 versions

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
This was an oversight, since few builds test on multiple OSes. But both Scala Native and the Cats Effect I/O-integrated JVM runtime are putting more pressure to check on other OSes.
> Only run fmt/header/mima etc. checks on primary os

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/373.
Just ran into this again, so now I've got a pretty good idea of what the user mistake is in this situation.
This error message would have helped in the original issue since we would have realized it's trying to mix Scala 2 and Scala 3 sources.
> Add helpful error for misplaced managed sources

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
By chance I stumbled on this flag today and h/t to @valencik and @samspills for concurrently discovering a scenario where it makes a difference in https://github.com/cozydev-pink/snakecase/pull/1.
Here is output of `scalac --help` for 3.2.2. Notice there is no `3.1-migration` option ...
```
-source  source version
Default 3.2
Choices 3.0-migration, 3.0, 3.1, 3.2-migration, 3.2, future-migration, future
```
> Use `-source:3.2-migration` on Scala 3.2 (when cross-compiling)

- .mergify.yml
- build.sbt
- mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyPlugin.scala
> Making mergifyLabelPaths overridable

- site/src/main/resources/org/typelevel/sbt/site/helium/site/styles.css
It should fix this:
Testing it on sbt-typelevel itself resulted in this for an h1:
> Fixing section title sizing for code blocks

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Reverts typelevel/sbt-typelevel#467, explanation in https://github.com/typelevel/sbt-typelevel/pull/467#issuecomment-1454299189.
> Revert "Use `-source:3.2-migration` on Scala 3.2 (when cross-compiling)"

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala
Follow-up to https://github.com/typelevel/sbt-typelevel/pull/451 that condenses the summaries a bit, which would be overwhelming for projects like http4s which have 3 scalas x 3 platforms x 10 platforms = 90 modules to report about :)
Tried it out here: https://github.com/armanbilge/fs2-dom/actions/runs/4328492513
If you unfold the "details" in test summary you get this:
> Condense GHA step summaries

- mergify/build.sbt
- mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyPlugin.scala
- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
`crossProjectCrossType` identifies the cross type of a cross project, so we know where the shared sources live (and thus where we should look for additional `scala-2.12-` and `scala-2.13+` source directories).
`crossProjectBaseDirectory` identifies the effective base directory of a project, useful for the mergify auto-labeling feature.
This should be more robust than our previous heuristical hacks.
Further reading:
- https://github.com/portable-scala/sbt-crossproject/pull/152
> Use new sbt-crossproject settings

- docs/secrets.md
In Discord, @armanbilge suggested adding a link to my script to the Secrets documentation. Open to suggestion on wording, placement, etc.
> document my 1Password / GitHub CLI script for setting up a new repo

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/419.
> Add `scalac-compat` dependency by default

- build.sbt
The organize imports rule is now buildin.
Follow up to: #522 
See https://github.com/scalacenter/scalafix/releases/tag/v0.11.0
> Cleanup after scalafix update

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
- Closes https://github.com/typelevel/sbt-typelevel/issues/474
- Merges https://github.com/typelevel/sbt-typelevel/pull/493
- Merges https://github.com/typelevel/sbt-typelevel/pull/515
- Heeds https://github.com/lampepfl/dotty/discussions/17591
- Closes https://github.com/typelevel/sbt-typelevel/issues/257
> Refresh scalac settings

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
This PR prepares the plugin for the official scala 3.3.0 release (it is tagged, just not released quite yet https://github.com/lampepfl/dotty/releases/tag/3.3.0). It adds back all the warnings for unused and discarded values that is re-added in this release.
> Add re-introduced unused/discard warnings for scala >3.3.0

- .github/workflows/ci.yml
- .mergify.yml
- build.sbt
- github-actions/src/main/scala/org/typelevel/sbt/gha/JavaSpec.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
1. We no longer use the typelevel/jdk-index. setup-java now includes all the JVMs we care about and overall seems well-maintained. I no longer think it's worth the effort to maintain our own index.
2. Closes https://github.com/typelevel/sbt-typelevel/issues/526. GraalVM now behaves like an ordinary Java distribution (i.e. it no longer has independent versioning).
> Use vanilla setup-java action, update setup-graalvm action

- docs/customization.md
- docs/faq.md
- docs/index.md
- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
I accidentally pushed 8912ce0c6b732e06cb3a3a03a763bd618c47ba28 directly to `main` 🙃 
Anyway, this PR provides notice and updates the docs. Typelevel itself has migrated to the new host, all newly registered group ids are using it, it's easy to migrate by opening an issue on the Sonatype JIRA, and it is still configurable to the old legacy host if needed, including by a global env variable / GHA secret.
> Make `s01.oss.sonatype.org` the default host

- build.sbt
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
- site/src/main/scala/org/typelevel/sbt/site/TypelevelProjects.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/399.
We don't currently do anything with this information, but we might in the future.
> Distinguish between org, affiliate projects in site plugin

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
- docs/customization.md
- docs/faq.md
We redefine the `prePR` command to hopefully give a better UX.
It now uses the idea from https://github.com/typelevel/sbt-typelevel/pull/210 to dynamically generate the `prePR` command depending on whether headers, scalafmt, and scalafix are enabled.
Closes https://github.com/typelevel/sbt-typelevel/issues/204#issue-1164304486. In that discussion we decided that `prePR` should be restricted to self-fixing things (i.e. headers, scalafmt, and scalafix).
Also closes https://github.com/typelevel/sbt-typelevel/issues/254 by deprecating `tlFatalWarningsInCi`. It no longer has a purpose in the new `prePR` command.
> Better `prePR` command

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Closes https://github.com/typelevel/sbt-typelevel/issues/205.
> `-release` -> `-java-output-version` in Scala 3.2

- core/src/main/scala/org/typelevel/sbt/BspControlPlugin.scala
- core/src/main/scala/org/typelevel/sbt/TypelevelBspPlugin.scala
Addresses #405.
Note: targets the `main` branch currently!
Introduces  a new `tlBspPlatforms` setting of `Set[Platform]` type that controls for which cross-project platforms the `bspEnabled` setting should be set to `true`. By default it becomes enabled for `JVMPlatform` only.
The new setting can be useful to reduce BSP activity for re-compiling projects while editing their code files. Platforms like `JSPlatform` and `NativePlatform` usually  recompile slower and consume more resources (JVM heap, in particular) upon compilation. 
**How to change the default**
```scala
tlBspPlatforms := Set(JVMPlatform, JSPlatform)
```
**How to opt out**
```scala
.disablePlugins(BspControlPlugin)
```
> BSP control plugin

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
Follow-up to https://github.com/typelevel/sbt-typelevel/pull/542
> `tlPrePRBotHook` should respect ci config

- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- no-publish/src/main/scala/org/typelevel/sbt/NoPublishPlugin.scala
The `noPublishProjectRefs` setting should always be available, even if the `NoPublishPlugin` is not used in the build (in which case `noPublishProjectRefs` is empty).
So we move the setting to its own plugin which is guaranteed to be triggered for every build, even builds that do not use `NoPublishPlugin`.
> Move `noPublishProjectRefs` to always-triggered plugin

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
> Clear sbt step preamble in dependency submission job

- .github/workflows/ci.yml
- .mergify.yml
- build.sbt
- github-actions/src/main/scala/org/typelevel/sbt/gha/JavaSpec.scala
* *deprecate* `Distribution.OpenJ9`
* *add* `Distribution.Semuru`
* *add* `Distribution. Microsoft`
https://github.com/actions/setup-java#supported-distributions
Followup to: #558
> Support new Java Distributions

- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowJob.scala
Bumps 2.13.6 default to ~~2.13.11~~ 2.13 (matching the behaviour of the generalisation to binary versions). Feel free to close if this is not desired!
> Corrected stale 2.13 version in WorkflowJob

- docs/site.md
The docs did not yet reflect recent changes:
* The setting is no longer `Boolean`.
* It is now populated based on the `organization` setting.
> docs for site plugin: adjust for recent changes to tlSiteIsTypelevelProject

- build.sbt
Since they include relevant documentation.
Closes https://github.com/typelevel/sbt-typelevel/issues/566.
> Link to sbt-dependency-submission and Scala Steward

- ci/src/main/scala/org/typelevel/sbt/CrossRootProject.scala
In some advanced cases it may be necessary to independently configure the `root`, `rootJVM`, `rootJS`, or `rootNative` project, instead of configuring them all together.
> Allow to independently configure components of `CrossRootProject`

- docs/faq.md
- site/src/main/scala/org/typelevel/sbt/site/TypelevelSiteSettings.scala
Changed the default Helium theme over to one more clearly embodying the typelevel colours as found on the main website. Reworked the colours and syntax highlighting. Colours taken from typelevel are clearly labelled as such.
Here is an example:
> New light theme for `sbt-typelevel-site`!

- .github/workflows/ci.yml
- build.sbt
This will enable site publishing from the `main` branch.
> Merge 0.4 -> main

- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
Or more correctly, sbt plugins support Maven properly, so javadoc.io can pick up our docs and publish them.
> javadoc.io now supports sbt plugins

- ci/src/main/scala/org/typelevel/sbt/CrossRootProject.scala
- docs/customization.md
- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
- mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala
We learned in https://github.com/typelevel/Laika/pull/451 that setting `crossScalaVersions := Nil` on the root project seems to be the trick to getting weird builds with "holes" to work, instead of this hack that was often broken.
> Deprecate `tlSkipIrrelevantScalas`

- docs/index.md
There is an unclosed bracket in the index page, presumably because the bracket ends with `;)`. Instead, I've replaced it with :wink: and a close paren.
> Fixed unclosed bracket in the index

- site/src/main/scala/org/typelevel/sbt/site/TypelevelSiteSettings.scala
Some people were unapply with the sheer in-your-face redness of the new theme introduced in #573, so this just inverts the primary and secondary colours, creating a bit better of a balance. With this, the lighter red is brought back, which is a bit more soft (but had bad contrast at the small sizes on the nav-bar), and the landing page changes from #586 have been incorporated.
However, the landing page in Laika is not particularly well set-up for light backgrounds, so while we wait for that to be properly decoupled (text colour-wise), there is an _**interim**_ darker landing page (note the button colour on that screenshot has since been altered):
Obviously, there is no default landing page for SBT typelevel currently, but this means the theme is currently a bit more future proofed. …
> New Theme Inversion

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- no-publish/src/main/scala/org/typelevel/sbt/NoPublishPlugin.scala
Added the binary scala suffix to the end of the module names for `Submit Dependencies`. The result of the change can be seen in the CI file. Fixes #597
> Added binary versions to `module-ignore` inputs

- .github/workflows/ci.yml
- build.sbt
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
Turns out, transitive dependencies of `test` are counted as `test-internal`, this is now ignored.
> Added `test-internal` to the ignored configs

- docs/index.md
It's not really a shell script, so better remove the `sh`.
> Fix syntax highlighting for g8 snippet

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/CrossRootProject.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
... and use it to fix the `+update` step. Previously there had been some complaint that this step was wasteful. Also, it turns out that it was broken 😂 apparently `reload` is not sufficient to fully reset the sbt state, specifically changes to the `project` ...
> Allow preamble to be skipped in `Sbt` step

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Due to an interaction of a scalac bug with shapeless derivation.
- https://github.com/scala/bug/issues/12072
- https://github.com/typelevel/sbt-tpolecat/issues/33
Also it is currently blocking the fs2 migration (see https://github.com/armanbilge/fs2/pull/4).
I haven't turned my brain on enough to appreciate the intrinsic value of this lint. Are we losing much by disabling it?
Edit: I guess the PR explains it in https://github.com/scala/scala/pull/8590.
Edit 2: so the primary use of implicit conversions is for syntax. And some Cats ops do take the target as by-name. But applying syntax to a multi-line block? Too weird 😅 I don't think we're missing much.
> Disable the `byname-implicit` lint on 2.13

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
This silences warnings cause by using `-Xsource:3` flag on Scala 2.13.
It turns out that the default behavior `-Xsource:3` is a bit tricky: it changes 2.13 semantics to match Scala 3, but then it also (fatally) warns you about those semantic changes. By adding this silencing, we can opt-in to the Scala 3 semantics without being warned about it.
This should silence two annoying warnings I'm aware of:
1. The warning on `package object`s that inherit from super-classes/traits. Our attempts to workaround this have gone very wrong e.g. https://github.com/typelevel/fs2/issues/3293.
2. A new one in Scala 2.13.12 where `case class`es with `private` constructors now raise a warning "constructor modifiers are assumed by synthetic `apply` method". Which is actually exactly the behavior we want. …
> Add `-Wconf:cat=scala3-migration:s` on 2.13

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
Fixes https://github.com/typelevel/sbt-typelevel/pull/639.
> `cat=scala3-migration` only exists in 2.13.12+

- github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala
Addresses https://github.com/scala/bug/issues/12867, ensuring that a slash is added for `2.13.12` and above (assuming that this will also be the case for `2.13.13` and `2.14.0` etc).
> Added version bound check and added slash

- .github/workflows/ci.yml
- ci-signing/src/main/scala/org/typelevel/sbt/TypelevelCiSigningPlugin.scala
> Glorious hack to fix publishing key import on macOS runners

- build.sbt
- site/build.sbt
- site/src/main/scala/org/typelevel/sbt/site/GenericSiteSettings.scala
- site/src/main/scala/org/typelevel/sbt/site/TypelevelHeliumExtensions.scala
This is a fairly trivial upgrade (mostly tweaking imports).
I kept all deprecations in place, if there is a desire for a cleanup, I'm happy to remove them, but I think those changes would best be kept in a separate PR. This is just the most minimal step to compile `sbt-typelevel` with Laika 1.x
> migrate to Laika 1.0.0

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
- docs/customization.md
- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
If I may say so myself: this is a significant improvement for usability 🎉  it makes it much much easier to define command aliases that depend on settings, and furthermore to composably modify the command aliases downstream.
> Introduce `tlCommandAliases` setting for defining command aliases

- kernel/src/main/scala/org/typelevel/sbt/TypelevelKernelPlugin.scala
- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
> removes the "compile-time" config in favor of "provided"

- settings/src/main/scala/org/typelevel/sbt/TypelevelSettingsPlugin.scala
When using generators that put sources in custom directories, eg [sbt-avro](https://github.com/sbt/sbt-avro) where the generated sources are by default is a dedicated folder in `sourceManaged / avro / $config` instead of `sourceManaged / $config`.
Using `sbt-typelevel` fails the `packageSrc` with this setup.
As the custom managed source path is added to the `managedSourceDirectories`, check the path given from the mapping is part of one of the source instead of the default `sourceManaged`.
> Allow packaging sources from all managed directories

- site/src/main/scala/org/typelevel/sbt/site/TypelevelSiteSettings.scala
Previously the color properties were all individual top level properties, drowning out the most relevant API elements. Secondly, their naming reflected the actual color, not their usage, which means that any changes in look & feel would lead to the need for new deprecations to avoid misleading names.
This PR moves all top level color properties into a new nested object `colors` and renames them so that they reflect their usage. The existing properties are all deprecated.
A possible change I would recommend, but did not do in this first version of the PR in case you want to be very conservative about it: I checked within the Typelevel organization, and not a single color property is used anywhere. So there is an option to remove these properties right away. In case you'd prefer that, too, …
> TypelevelSiteSettings - deprecate top level color properties in favor of a nested object

- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
Closes https://github.com/typelevel/sbt-typelevel/pull/698.
> Do not set a default `startYear`

- build.sbt
- ci/src/main/scala/org/typelevel/sbt/CrossRootProject.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/Concurrency.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/JobContainer.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/JobEnvironment.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/PREventType.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/Paths.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/PermissionScope.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/Ref.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/RefPredicate.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/UseRef.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowJob.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
- mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyAction.scala
- mergify/src/main/scala/org/typelevel/sbt/mergify/MergifyStewardConfig.scala
So that we have a better chance to evolve these compatibly in the future, as needed.
> The great de-case-classification

- .github/workflows/ci.yml
- build.sbt
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
- https://github.com/sbt/sbt-github-actions/issues/179
> Support `working-directory` in `WorkflowStep.Run`

- .github/workflows/ci.yml
- site/src/main/scala/org/typelevel/sbt/TypelevelSitePlugin.scala
Bumps the dep so that the warning about Node v16 being deprecated (when the site gets published) will disappear.
See https://github.com/peaceiris/actions-gh-pages/blob/v4.0.0/CHANGELOG.md#400-2024-04-08
> Bump peaceiris/actions-gh-pages to 4.0.0

- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
Generating this step even when unnecessary is harmless and will fix the problem in https://github.com/typelevel/fs2/pull/3431.
> Always generate macOS `brew install sbt` step

- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala
- docs/customization.md
The sbt-java-formatter plugin exposes a `javafmtCheckAll` command.
https://github.com/sbt/sbt-java-formatter
> Support checking Java formatting

- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/GitHubActionsPlugin.scala
- sonatype-ci-release/src/main/scala/org/typelevel/sbt/TypelevelSonatypeCiReleasePlugin.scala
Currently, if you publish to the new Sonatype Central repository (#721), during publishing you'll encounter the following issue:
```
[error] scala.MatchError: URLRepository(https://settingkey/(This / This / This / sonatypeCredentialHost), Patterns(ivyPatterns=Vector(), artifactPatterns=Vector(), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), false) (of class sbt.librarymanagement.URLRepository)
```
It happens in the code that computes a step summary. Originally, I tried to write a rendering function for the entire `URLRepository`, but serializing `Patterns` is a bit tedious and the step summary isn't all that useful, so I figured we can start with an empty string for now.
> Fallback on non-MavenRepository repos

- sonatype/src/main/scala/org/typelevel/sbt/TypelevelSonatypePlugin.scala
To be consistent with changes in https://github.com/xerial/sbt-sonatype/commit/70740908a72b9bbafb9cca82ec77f8db215be7f4. Fixes issue reported in https://github.com/typelevel/sbt-typelevel/issues/721#issuecomment-2254259473.
> Set `sonatypeCredentialHost` at build-level

- github-actions/mima.sbt
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowJob.scala
- Added `with*` methods for `WorkflowJob` for symmetry with `WorkflowStep`
> Add `with*` methods for `WorkflowJob`

- .github/workflows/ci.yml
- ci/src/main/scala/org/typelevel/sbt/TypelevelCiPlugin.scala
- docs/customization.md
This tries to fix the following issue in forked repositories:
```
[error] Unexpected status 404 Not Found with body:
[error] {"message":"The Dependency graph is disabled for this repository. Please enable it before submitting snapshots.","documentation_url":"https://docs.github.com/rest/dependency-graph/dependency-submission#create-a-snapshot-of-dependencies-for-a-repository","status":"404"}
```
Example: https://github.com/danicheg/cats/actions/runs/10027887278/job/27714122616#step:10:554
> Do not run the 'dependency-submission' job in CI for forked repositories

- .github/workflows/ci.yml
- github-actions/src/main/scala/org/typelevel/sbt/gha/JavaSpec.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowStep.scala
Since v4.4.0 graalvm can be installed using setup-java https://github.com/actions/setup-java/releases/tag/v4.4.0 (for legacy versions setup-graalvm is still needed)
Not sure if we need to expose these additional distributions: 
- https://github.com/actions/setup-java/releases/tag/v4.3.0 supports SapMachine 
- https://github.com/actions/setup-java/releases/tag/v3.13.0 supports Dragonwell
> Use `actions/setup-java` to install GraalVM

- sonatype/build.sbt
... to restore Java 8 support.
- https://github.com/xerial/sbt-sonatype/issues/530
Reverts https://github.com/typelevel/sbt-typelevel/pull/754.
> Revert "Update sbt-sonatype to 3.12.0"

- .github/workflows/ci.yml
- .mergify.yml
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativeKeys.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
- github-actions/src/main/scala/org/typelevel/sbt/gha/WorkflowJob.scala
This week we saw a lot of chaos because the `ubuntu-latest` runner tag was switched to the `ubuntu-24.04` image, away from the `ubuntu-22.04` image[^1]. 
I'm proposing that we pin the ubuntu runner OS to 22.04 as the default value so we can avoid that chaos in the future. By pinning we can
- test here before updating to a new runner tag, preventing CI for sbt-typelevel users from breaking unexpectedly (breaking due to this kind of change at least lol)
- communicate with users via a major release + release notes if a major change like this happens again
[^1]: And that switch is now being [rolled back](https://github.com/actions/runner-images/issues/10636#issuecomment-2417293457) for the time being 😵
> pin to ubuntu-22.04 as default runner OS

- .github/workflows/ci.yml
- .mergify.yml
- github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativePlugin.scala
Before
After:
**Feedback welcome.**
I really dislike this part of the GH UI
> Trying a shorter job name for better display in GHA

- kernel/src/main/scala/org/typelevel/sbt/kernel/V.scala
- kernel/src/test/scala/org/typelevel/sbt/kernel/VSuite.scala
There was a minor issue where if a commit was tagged with both an RC and a final release, "v0.6.0-RC1" and "v0.6.0", the current version would be the most recent RC and not the final version.  This PR switches the bias on sort, so prereleases come before final releases.
> Change sort order of versions so final releases are last not first.

- .github/workflows/ci.yml
- .mergify.yml
- build.sbt
The `windows-latest` tag currently points to Windows Server 2022 but **it will be migrating to point to Windows Server 2025 starting on September 2 2025**
We can keep using the existing runner by switching to the `windows-2022` tag. This runner will have another 3 years of support and we can migrate in the future under less of a crunch. Please don't feel you have to accept this PR if you would rather make the switch now, I'm just trying to make sure maintainers are aware and not surprised like we all were with the ubuntu-latest changes.
Details about the runner change, and what other software changes are being made alongside, are documented here:
- https://github.com/actions/runner-images/issues/12677
> Switch to `windows-2022` runner tag
